<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Appointment;
use App\Models\Doctor;

class PatientDashboardController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        $appointments = Appointment::where('patient_id', $user->id)
            ->orderBy('appointment_date', 'asc')
            ->get();

        $stats = [
            'total' => $appointments->count(),
            'upcoming' => $appointments->where('status', 'scheduled')->count(),
            'completed' => $appointments->where('status', 'completed')->count(),
            'cancelled' => $appointments->where('status', 'cancelled')->count(),
        ];

        // Annotate each upcoming appointment with the doctor's current live token
        $upcomingAppointments = $appointments->where('status', 'scheduled')->map(function ($appt) {
            $doctorProfile = Doctor::where('user_id', $appt->doctor_id)->first();
            $appt->current_token = $doctorProfile ? $doctorProfile->current_token : 0;
            $appt->live_status   = $doctorProfile ? $doctorProfile->live_status : 'Unavailable';
            return $appt;
        });

        // Fetch any prescriptions that are pending but ALREADY have a bill generated by pharmacist
        $pendingBills = \App\Models\Prescription::with(['doctor', 'bill'])
            ->where('patient_id', $user->id)
            ->where('status', 'pending')
            ->whereHas('bill')
            ->get();

        return view('patient.dashboard', [
            'user'                 => $user,
            'stats'                => $stats,
            'upcomingAppointments' => $upcomingAppointments,
            'pendingBills'         => $pendingBills
        ]);
    }

    public function payBill(Request $request, \App\Models\Prescription $prescription)
    {
        if ($prescription->patient_id !== Auth::id()) {
            abort(403);
        }

        $amount = ($prescription->bill->total_amount ?? 0) * 100; // Razorpay expects amount in paise

        if ($amount <= 0) {
            return response()->json(['error' => 'Invalid bill amount.'], 400);
        }

        // Create Razorpay Order via HTTP Client
        $keyId = env('RAZORPAY_KEY_ID');
        $keySecret = env('RAZORPAY_KEY_SECRET');

        $response = \Illuminate\Support\Facades\Http::withoutVerifying()
            ->withBasicAuth($keyId, $keySecret)
            ->post('https://api.razorpay.com/v1/orders', [
                'amount' => $amount,
                'currency' => 'INR',
                'receipt' => 'rcpt_' . $prescription->id,
            ]);

        if ($response->successful()) {
            return response()->json([
                'order_id' => $response->json()['id'],
                'amount' => $amount,
                'key' => $keyId,
                'name' => 'MedFlow Healthcare',
                'description' => 'Prescription Bill #' . $prescription->id,
                'user_name' => Auth::user()->name,
                'user_email' => Auth::user()->email,
                'user_phone' => Auth::user()->phone ?? '',
            ]);
        }

        return response()->json(['error' => 'Failed to create payment order.'], 500);
    }

    public function verifyPayment(Request $request, \App\Models\Prescription $prescription)
    {
        $input = $request->all();
        $keySecret = env('RAZORPAY_KEY_SECRET');

        // Verify Razorpay Signature
        $attributes = [
            'razorpay_order_id' => $input['razorpay_order_id'],
            'razorpay_payment_id' => $input['razorpay_payment_id'],
            'razorpay_signature' => $input['razorpay_signature']
        ];

        $expectedSignature = hash_hmac('sha256', $attributes['razorpay_order_id'] . '|' . $attributes['razorpay_payment_id'], $keySecret);

        if ($expectedSignature === $attributes['razorpay_signature']) {
            // Payment Successful
            $prescription->update(['status' => 'completed']);
            
            if ($prescription->appointment) {
                $prescription->appointment->update(['status' => 'completed']);
            }

            // Update bill status if you have a status column in bills
            if ($prescription->bill) {
                $prescription->bill->update(['payment_status' => 'paid', 'transaction_id' => $input['razorpay_payment_id']]);
            }

            return response()->json(['success' => true]);
        }

        return response()->json(['success' => false, 'error' => 'Payment verification failed.'], 400);
    }
}